artifact_uri: file:///D:/Especializacion/Productos_de_datos/entorno/PRE-08-mlflow-tracking-local-semontoyava/my_mlruns/732043413508132086/e8e7bfd2e56d45288155d255c5d1aceb/artifacts
end_time: 1748472534513
entry_point_name: ''
experiment_id: '732043413508132086'
lifecycle_stage: active
run_id: e8e7bfd2e56d45288155d255c5d1aceb
run_name: elasticnet_a853a430
run_uuid: e8e7bfd2e56d45288155d255c5d1aceb
source_name: ''
source_type: 4
source_version: ''
start_time: 1748472534446
status: 3
tags: []
user_id: Admin
